### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by c-schwarze** [betheluniversity/sciencelabs-python#1]
Symfony created log files automatically.

Can we have an error.log file? Maybe its more fitting to have an info.log or messages.log file, but I want to be able to log transactions. Specifically, when students sign in/out because the current lab has had issues with that. So additional logging will help us either figure that out, or just provide more data when there are issues.

**Comment by c-schwarze** [comment]
@j-jasik if you ever need something to do, this would be a good one to work on

**Comment by j-jasik** [comment]
Sentry logs all errors, and there is a session log that tracks all open session transactions.
