### ISSUE TITLE
XP Notification Banner

### ISSUE THREAD

**Issue by j-jasik** [betheluniversity/sciencelabs-python#109]
We should have some kind of banner when you are on XP letting you know you are on XP. Probably similar to staging.bethel.edu

**Comment by c-schwarze** [comment]
Hmm. I'm having second thoughts on this. It could get annoying when you are acting as a user. And we won't be doing much active XP development in a few weeks. So maybe this isn't as helpful as we thought?

**Comment by j-jasik** [comment]
Sounds good. I'll close it for now and we can revisit it later if we think it's worth it.
