### ISSUE TITLE
Form Repopulation

### ISSUE THREAD

**Issue by j-jasik** [betheluniversity/sciencelabs-python#117]
There are a few places where certain checks cause a page with a form to be reloaded. Two places I can think of for sure are the create session and the create schedule pages. The reload doesn't repopulate the form data, which would be really nice if it did.

**Comment by bam95899** [comment]
Possibly taken care of in PR #127

**Comment by bam95899** [comment]
Possibly fixed in PR #127

**Comment by c-schwarze** [comment]
@j-jasik can you chime in next time you are in?

**Comment by j-jasik** [comment]
I just went through and looked at this, and I think everything looks good! I'll close the issue.
