### ISSUE TITLE
Add loading buffer to user search

### ISSUE THREAD

**Issue by j-jasik** [betheluniversity/sciencelabs-python#123]
Right now there's no good way to see if anything is happening after you click "search" on the search users page. I feel like there should be something there to let the user know the search is happening. There's a pause where you can't tell if it's working or not.

**Comment by c-schwarze** [comment]
Ah, thats a good idea. For other applications, we have just used a gif with a transparent background.

**Comment by bam95899** [comment]
Fixed in PR #125
