### ISSUE TITLE
Search reads from all columns

### ISSUE THREAD

**Issue by c-schwarze** [betheluniversity/sciencelabs-python#156]
The search triggers things for the string, "Act as user". So a search for "act", doesn't bring up what you would expect. Search should only apply to users' values.
![Screen Shot 2019-08-30 at 11 10 19 AM](https://user-images.githubusercontent.com/7849657/64035648-ea2c4680-cb16-11e9-9429-27ad3afcb222.png)

**Comment by j-jasik** [comment]
Fixed
