### ISSUE TITLE
Update semester list on semester startup

### ISSUE THREAD

**Issue by j-jasik** [betheluniversity/sciencelabs-python#180]
Since the list of semesters is stored in the flask session, after a new semester is started up it doesn't appear in any of the dropdowns until the user gets a new flask session. This should be fixed to update immediately somehow.

**Comment by bam95899** [comment]
@j-jasik this is working locally and on xp without me making any changes. Are there any steps you know of that could recreate this issue?

**Comment by j-jasik** [comment]
We should look at this together the next time we're both in.
