### ISSUE TITLE
Use a MySQL Database

### ISSUE THREAD

**Issue by c-schwarze** [betheluniversity/sciencelabs-python#2]
For now, we can probably just use MySQL locally for testing purposes. You can grab a copy of a db from the server (h5). 

Eventually, we will want to work with Mike Johnson to get our DB connected to a remote MySQL DB. However, you are welcome to start off with a "correct" DB. If you do this, you won't have to duplicate the work.

**Comment by j-jasik** [comment]
Database stuff is pretty much good to go. We are hooked up to the development database, and it should only be a matter of changing one line in the config for the production database.
