### ISSUE TITLE
Term Startup Testing

### ISSUE THREAD

**Issue by j-jasik** [betheluniversity/sciencelabs-python#99]
We need to go through and make sure setting up a term works well. The following should happen:

- When the new term is set that term should become active, while the old term is not anymore
- All students (where student is their only role) should be soft deleted
- All lead tutors get demoted to regular tutors
- The populate courses cron runs to pull in banner courses. This also handles creating any new professors, courses, and verifies that the term is set.
- When the user who is setting up the term goes to the Courses page (the one on the main nav) they should see the new courses pulled in and be able to add new, valid coursecodes (I'm not sure how we'll test this part)
- When they go to the Users page they shouldn't see any students (unless a user has multiple roles and student is one of them) or lead tutors. They will have to promote the leads manually and add in any newly hired tutors.
- They should not see any schedules on the Schedule page, but they should be able to make as many schedules as they need, assigning tutors.
- Once schedules are made the sessions and tutorSessions should get automatically created, so if they go to Available Sessions on the Session page there should be a whole list them, with the tutors assigned correctly.
- The Closed sessions page and the restore session page should not have any info
- We should also go through the reports pages to make sure none of them fail after the new term is created.

I wrote a lot of the logic for this stuff, so feel free to look through it and ask questions. I had it working when I first went through, but a lot has changed since then and I haven't looked at this stuff in a while.

**Comment by bam95899** [comment]
- [ ] When the new term is set that term should become active, while the old term is not anymore

- [ ]

**Comment by bam95899** [comment]
- [ ] When the new term is set that term should become active, while the old term is not anymore

- [ ] All students (where student is their only role) should be soft deleted

- [ ] All lead tutors get demoted to regular tutors

- [ ] The populate courses cron runs to pull in banner courses. This also handles creating any new professors, courses, and verifies that the term is set.

- [ ] When the user who is setting up the term goes to the Courses page (the one on the main nav) they should see the new courses pulled in and be able to add new, valid coursecodes (I'm not sure how we'll test this part)

- [ ] When they go to the Users page they shouldn't see any students (unless a user has multiple roles and student is one of them) or lead tutors. They will have to promote the leads manually and add in any newly hired tutors.

- [ ] They should not see any schedules on the Schedule page, but they should be able to make as many schedules as they need, assigning tutors.

- [ ] Once schedules are made the sessions and tutorSessions should get automatically created, so if they go to Available Sessions on the Session page there should be a whole list them, with the tutors assigned correctly.

- [ ] The Closed sessions page and the restore session page should not have any info
We should also go through the reports pages to make sure none of them fail after the new term is created.

**Comment by c-schwarze** [comment]
Nice work with the checkboxes 👍

**Comment by j-jasik** [comment]
That's cool! I didn't realize you could do that.

**Comment by c-schwarze** [comment]
https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet

**Comment by bam95899** [comment]
``` The populate courses cron runs to pull in banner courses. This also handles creating any new professors, courses, and verifies that the term is set.``` 

Can't really test this but looking over the code it seems as if everything you said should happen is theoretically happening. It looks like new coursecodes are being made, professors, courses, and course professors are either being activated or created depending on their existence in the DB.

**Comment by bam95899** [comment]
All issues but the last two were fixed/checked in PR #122
